### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by amy-hs** [ngauthier/capybara-slow_finder_errors#19]
👋 Will there be a new release to capture these commits? I see that the last release (`0.1.5`) was from 2018. Thank you!

<img width="514" alt="Screen Shot 2023-05-22 at 16 04 48" src="https://github.com/ngauthier/capybara-slow_finder_errors/assets/94405478/a626495f-1a13-4d32-a99b-404a798c21f8">

**Comment by ngauthier** [comment]
Hi Amy, I merge what people send me but I really don't do much with this gem. You can source the gem from github to a particular commit if you'd like.

**Comment by amy-hs** [comment]
No worries, I can point it to a specific commit 👍 Thank you!
